Repository AGr2020Xman/Project_1-Basketball-News, pull requests merged in 2020-10, with the labels that each got.

#39 Frontend- @media's, Img and font sizing
  img/slime.png
  style.css
Labels: documentation, enhancement

#40 Version 2 - some html minor updates + styling to compare against M's master
  index.html
  script.js
  style.css
Labels: documentation, enhancement

#44 fixing duplication
  index.html
  style.css
Labels: help wanted

#45 duplication! >.< FIX
  index.html
  style.css
Labels: duplicate
